# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='profile',
        ),
    ]
