# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180310_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
